
page_enum = [
    '0x0:', 'SectionID::Power_Off_Wii:',
    '0x4:', 'SectionID::Return_To_Wii_Menu_1:',
    '0x5:', 'SectionID::Return_To_Wii_Menu_2:',
    '0x6:', 'SectionID::Test_6:',
    '0x7:', 'SectionID::Test_7:',
    '0x8:', 'SectionID::Test_8:',
    '0x9:', 'SectionID::Test_9:',
    '0xa:', 'SectionID::Test_A:',
    '0xb:', 'SectionID::Test_B:',
    '0xc:', 'SectionID::Test_C:',
    '0xd:', 'SectionID::Test_D:',
    '0xe:', 'SectionID::Test_E:',
    '0xf:', 'SectionID::Test_F:',
    '0x10:', 'SectionID::Create_New_Save:',
    '0x11:', 'SectionID::Corrupted_Save:',
    '0x12:', 'SectionID::Country_Changed:',
    '0x13:', 'SectionID::Game_Cannot_Be_Saved:',
    '0x14:', 'SectionID::Cannot_Access_System_Memory:',
    '0x15:', 'SectionID::Cannot_Access_Mii_Data:',
    '0x16:', 'SectionID::ESRB_Notice:',
    '0x17:', 'SectionID::Recommend_60Hz_1:',
    '0x18:', 'SectionID::Recommend_60Hz_2:',
    '0x19:', 'SectionID::Grand_Prix_Panorama:',
    '0x1a:', 'SectionID::VS_Race_Panorama:',
    '0x1b:', 'SectionID::Balloon_Battle_Panorama:',
    '0x1c:', 'SectionID::Mission_Boss_Panorama:',
    '0x1d:', 'SectionID::Tournament_Boss_Panorama:',
    '0x1e:', 'SectionID::Grand_Prix_Gameplay:',
    '0x1f:', 'SectionID::Time_Trial_Gameplay:',
    '0x20:', 'SectionID::S_1P_VS_Race_Gameplay:',
    '0x21:', 'SectionID::S_2P_VS_Race_Gameplay:',
    '0x22:', 'SectionID::S_3P_VS_Race_Gameplay:',
    '0x23:', 'SectionID::S_4P_VS_Race_Gameplay:',
    '0x24:', 'SectionID::S_1P_Team_VS_Race_Gameplay:',
    '0x25:', 'SectionID::S_2P_Team_VS_Race_Gameplay:',
    '0x26:', 'SectionID::S_3P_Team_VS_Race_Gameplay:',
    '0x27:', 'SectionID::S_4P_Team_VS_Race_Gameplay:',
    '0x28:', 'SectionID::S_1P_Battle_Gameplay:',
    '0x29:', 'SectionID::S_2P_Battle_Gameplay:',
    '0x2a:', 'SectionID::S_3P_Battle_Gameplay:',
    '0x2b:', 'SectionID::S_4P_Battle_Gameplay:',
    '0x2c:', 'SectionID::Mission_Mode_Gameplay:',
    '0x2d:', 'SectionID::Tournament_Gameplay:',
    '0x2e:', 'SectionID::Grand_Prix_Replay:',
    '0x2f:', 'SectionID::Time_Trial_Replay:',
    '0x30:', 'SectionID::Ghost_Race_Gameplay_1:',
    '0x31:', 'SectionID::Ghost_Race_Gameplay_2:',
    '0x32:', 'SectionID::Watch_Ghost_From_Channel:',
    '0x33:', 'SectionID::Watch_Ghost_From_Downloads:',
    '0x34:', 'SectionID::Watch_Ghost_From_Menu:',
    '0x35:', 'SectionID::Grand_Prix_Award:',
    '0x36:', 'SectionID::VS_Race_Award:',
    '0x37:', 'SectionID::Award_37:',
    '0x38:', 'SectionID::Award_38:',
    '0x39:', 'SectionID::Ending_Normal_A:',
    '0x3a:', 'SectionID::Ending_True_A:',
    '0x3b:', 'SectionID::Ending_Normal_B:',
    '0x3c:', 'SectionID::Ending_True_B:',
    '0x3d:', 'SectionID::Congratulations:',
    '0x3e:', 'SectionID::Congratulations_Complete:',
    '0x3f:', 'SectionID::Main_Menu_From_Boot:',
    '0x40:', 'SectionID::Main_Menu_From_Reset:',
    '0x41:', 'SectionID::Main_Menu_From_Menu:',
    '0x42:', 'SectionID::Main_Menu_From_New_License:',
    '0x43:', 'SectionID::Main_Menu_From_License_43:',
    '0x44:', 'SectionID::Demo:',
    '0x45:', 'SectionID::Mii_Select_1:',
    '0x46:', 'SectionID::Mii_Select_2:',
    '0x47:', 'SectionID::License_Settings:',
    '0x48:', 'SectionID::Single_Player_From_Menu:',
    '0x49:', 'SectionID::Single_Player_TT_Change_Chara:',
    '0x4a:', 'SectionID::Single_Player_TT_Change_Course:',
    '0x4b:', 'SectionID::Single_Player_VS_Next_Race:',
    '0x4c:', 'SectionID::Single_Player_BT_Next_Battle:',
    '0x4d:', 'SectionID::Single_Player_MR_Choose_Mission:',
    '0x4e:', 'SectionID::Single_Player_Chan_Race_Ghost:',
    '0x4f:', 'SectionID::Single_Player_LB_Race_Ghost:',
    '0x50:', 'SectionID::Single_Player_List_Race_Ghost:',
    '0x51:', 'SectionID::Send_Ghost_To_Friend:',
    '0x52:', 'SectionID::Race_Ghost_From_Chan_Boot:',
    '0x53:', 'SectionID::Watch_Replay_From_Chan_Boot:',
    '0x54:', 'SectionID::Local_Multiplayer:',
    '0x55:', 'SectionID::S_1P_Wifi:',
    '0x56:', 'SectionID::S_1P_Wifi_Globe_Disconnect:',
    '0x57:', 'SectionID::S_1P_Wifi_From_Find_Friend:',
    '0x58:', 'SectionID::S_1P_Wifi_VS_Voting:',
    '0x59:', 'SectionID::S_1P_Wifi_Battle_Voting:',
    '0x5a:', 'SectionID::S_2P_Wifi_Select_Mii:',
    '0x5b:', 'SectionID::S_2P_Wifi:',
    '0x5c:', 'SectionID::S_2P_Wifi_Globe_Disconnect:',
    '0x5d:', 'SectionID::Unknown_5D:',
    '0x5e:', 'SectionID::S_2P_Wifi_VS_Voting:',
    '0x5f:', 'SectionID::S_2P_Wifi_Battle_Voting:',
    '0x60:', 'SectionID::S_1P_Wifi_Friend_Room_VS_Voting:',
    '0x61:', 'SectionID::S_1P_Wifi_Friend_Room_Team_VS_Voting:',
    '0x62:', 'SectionID::S_1P_Wifi_Friend_Room_Balloon_Voting:',
    '0x63:', 'SectionID::S_1P_Wifi_Friend_Room_Coin_Voting:',
    '0x64:', 'SectionID::S_2P_Wifi_Friend_Room_VS_Voting:',
    '0x65:', 'SectionID::S_2P_Wifi_Friend_Room_Team_VS_Voting:',
    '0x66:', 'SectionID::S_2P_Wifi_Friend_Room_Balloon_Voting:',
    '0x67:', 'SectionID::S_2P_Wifi_Friend_Room_Coin_Voting:',
    '0x68:', 'SectionID::S_1P_Wifi_VS_Gameplay:',
    '0x69:', 'SectionID::S_2P_Wifi_VS_Gameplay:',
    '0x6a:', 'SectionID::S_1P_Wifi_VS_Live_View:',
    '0x6b:', 'SectionID::S_2P_Wifi_VS_Live_View:',
    '0x6c:', 'SectionID::S_1P_Wifi_BT_Gameplay:',
    '0x6d:', 'SectionID::S_2P_Wifi_BT_Gameplay:',
    '0x6e:', 'SectionID::S_1P_Wifi_BT_Live_View:',
    '0x6f:', 'SectionID::S_2P_Wifi_BT_Live_View:',
    '0x70:', 'SectionID::S_1P_Wifi_Friend_VS_Gameplay:',
    '0x71:', 'SectionID::S_1P_Wifi_Friend_Team_VS_Gameplay:',
    '0x72:', 'SectionID::S_1P_Wifi_Friend_Balloon_BT_Gameplay:',
    '0x73:', 'SectionID::S_1P_Wifi_Friend_Coin_BT_Gameplay:',
    '0x74:', 'SectionID::S_2P_Wifi_Friend_VS_Gameplay:',
    '0x75:', 'SectionID::S_2P_Wifi_Friend_Team_VS_Gameplay:',
    '0x76:', 'SectionID::S_2P_Wifi_Friend_Balloon_BT_Gameplay:',
    '0x77:', 'SectionID::S_2P_Wifi_Friend_Coin_BT_Gameplay:',
    '0x78:', 'SectionID::Wifi_Disconnect_Error:',
    '0x79:', 'SectionID::Wifi_Disconnect_General:',
    '0x7a:', 'SectionID::Channel_From_Menu:',
    '0x7b:', 'SectionID::Channel_From_Check_Rankings:',
    '0x7c:', 'SectionID::Channel_From_Downloads:',
    '0x7d:', 'SectionID::Time_Trial_Leaderboards:',
    '0x7e:', 'SectionID::Tournament_Leaderboards:',
    '0x7f:', 'SectionID::Ghost_Race_With_Data:',
    '0x80:', 'SectionID::Ghost_Race_Without_Data:',
    '0x81:', 'SectionID::Ghost_Race_Next_Race:',
    '0x82:', 'SectionID::Downloaded_Ghost_Data:',
    '0x83:', 'SectionID::Friends_List_1:',
    '0x84:', 'SectionID::Friends_List_2:',
    '0x85:', 'SectionID::Tournament:',
    '0x86:', 'SectionID::Tournament_Change_Chara:',
    '0x87:', 'SectionID::Tournament_Submit_Record:',
    '0x88:', 'SectionID::Tournament_Wii_Wheel_Only:',
    '0x89:', 'SectionID::Tournament_Wii_Wheel_Only_Bosses:',
    '0x8a:', 'SectionID::Invite_Friends_From_Msg_Board:',
    '0x8b:', 'SectionID::Download_Latest_Data:',
    '0x8c:', 'SectionID::Options:',
    '0x8d:', 'SectionID::Install_Channel:',
    '0x8e:', 'SectionID::Choose_Region:',
    '0x8f:', 'SectionID::Join_Message_Service:',
    '0x90:', 'SectionID::Msg_Unlock_Pink:',
    '0x91:', 'SectionID::Msg_Unlock_Orange:',
    '0x92:', 'SectionID::Msg_Unlock_Blue:',
    '0x93:', 'SectionID::Msg_Unlock_Yellow:',
    '0x94:', 'SectionID::Broken_Mission_Mode_Menu:',
]


f = open("sectionaddpages.txt")
data = f.readlines()
f.close()

with open('file_out.txt', 'w') as fo:
    for line in data:
        newline = line
        for i in range(len(page_enum) >> 1):
            newline = line.replace(page_enum[i * 2], page_enum[(i * 2) + 1])
            if (newline != line):
                break
        fo.write(newline)



